### ISSUE TITLE
pedantic 1.9.0 cause error

### ISSUE THREAD

**Issue by guyulmaz** [cbonello/baseball#1]
Because baseball depends on flutter_test any from sdk which depends on pedantic 1.8.0+1, pedantic 1.8.0+1 is required.

**Comment by cbonello** [comment]
Yes, that's a known issue (see [#48246](https://github.com/flutter/flutter/issues/48246)). I have added a dependency override in `pubspec.yaml` to use pedantic 1.9.0 for now. And I fixed all the warning caused by the newly enabled `omit_local_variable_types` linter rule.
