### ISSUE TITLE
getGameSchedule(String date) date format error

### ISSUE THREAD

**Issue by guyulmaz** [cbonello/baseball#3]
//String _formatDate() => formatDate(_selectedDate, <String>[dd, '/', mm, '/', yyyy]);
  String _formatDate() => formatDate(_selectedDate, <String>[mm, '/', dd, '/', yyyy]);

https://statsapi.mlb.com/api/v1/schedule/?sportId=1&startDate=03/25/2020&endDate=03/26/2020&fields=dates,games,gamePk,gameDate,status,detailedState,venue,teams,score,leagueRecord,wins,losses,team,name,isWinner

statsapi request mm/dd/yyyy

**Comment by cbonello** [comment]
Thanks Göksel, good catch. The app works a lot better now!
