### ISSUE TITLE
web support

### ISSUE THREAD

**Issue by guyulmaz** [cbonello/baseball#4]
Hello,
I changed to beta channel and tried flutter web. It is giving error.
Maybe it can be a good idea to make it also work at web.
I don't know if some libraries are web ready or not.
Kind regards,

**Comment by cbonello** [comment]
Hi, The package was not developed with flutter web in mind. But I'll ave a look. Thanks.

**Comment by cbonello** [comment]
Issue was related to [Mobx: Maximum call stack size exceeded for private @actions returning Futures #438](https://github.com/mobxjs/mobx.dart/issues/438)

Commit [10fb20db4ebc43347b31f6768eea4e700017dab2 ](https://github.com/cbonello/baseball/commit/10fb20db4ebc43347b31f6768eea4e700017dab2) fixes the issue.
